type Comment {
    _id: ID!
    comment: String!
    author: User!
    post: Post!
}

input CommentInput {
    comment: String!
    author: ID!
    post: ID!
}

type Query {
    comments: [Comment!]!
    comment(id: ID!): Comment!
}

type Mutation {
    createComment(data: CommentInput!): Comment!
    updateComment(id: ID, data: CommentInput!): Comment!
    deleteComment(id: ID!): Boolean
}